# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ChessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChessApp
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'PromiseKit'

end
